# harness-core.psm1

$ExecutionStatePath = "$PSScriptRoot\..\..\.agents\state\execution.json"
$TaskProjectionPath = "$PSScriptRoot\..\..\.agents\state\task.md"
$HashesPath = "$PSScriptRoot\hashes.json"

function Get-HarnessIntegrity {
    if (-not (Test-Path $HashesPath)) {
        return $false
    }
    
    $expectedHashes = Get-Content $HashesPath | ConvertFrom-Json
    $scripts = Get-ChildItem "$PSScriptRoot\*.ps1"
    
    foreach ($script in $scripts) {
        $hash = (Get-FileHash $script.FullName -Algorithm SHA256).Hash
        $name = $script.Name
        if ($expectedHashes.$name -ne $hash) {
            Write-Host "Integrity violation: $name has been modified." -ForegroundColor Red
            return $false
        }
    }
    return $true
}

function Invoke-FailClosed {
    param([string]$Reason)
    Write-Host "FAIL-CLOSED: $Reason" -ForegroundColor Red
    
    if (Test-Path $ExecutionStatePath) {
        $state = Get-Content $ExecutionStatePath -Raw | ConvertFrom-Json
        $state.current_state = "BLOCKED_ESCALATED"
        $state | ConvertTo-Json -Depth 10 | Set-Content $ExecutionStatePath
        Update-TaskProjection
    }
    exit 1
}

function Read-ExecutionState {
    if (-not (Test-Path $ExecutionStatePath)) {
        Invoke-FailClosed "execution.json not found."
    }
    
    if (-not (Get-HarnessIntegrity)) {
        Invoke-FailClosed "Harness integrity check failed."
    }
    
    try {
        $state = Get-Content $ExecutionStatePath -Raw | ConvertFrom-Json
        
        # Schema validation (structural)
        if ($null -eq $state.current_state -or $null -eq $state.verification -or $null -eq $state.workstreams -or $null -eq $state.pr_info) {
            Invoke-FailClosed "execution.json schema violation."
        }
        
        return $state
    } catch {
        Invoke-FailClosed "Failed to parse execution.json."
    }
}

function Write-ExecutionState {
    param($State)
    $State | ConvertTo-Json -Depth 10 | Set-Content $ExecutionStatePath
    Update-TaskProjection
}

function Update-TaskProjection {
    if (-not (Test-Path $ExecutionStatePath)) { return }
    $state = Get-Content $ExecutionStatePath -Raw | ConvertFrom-Json
    
    $md = "# Task State (READ-ONLY PROJECTION)`n`n"
    $md += "**DO NOT EDIT THIS FILE DIRECTLY. It is generated from execution.json.**`n`n"
    $md += "**Current State:** $($state.current_state)`n"
    $md += "**Current Phase:** $($state.current_phase)`n`n"
    
    $md += "## Pull Request`n"
    if ($state.pr_info.number) {
        $md += "- PR Number: $($state.pr_info.number)`n"
        $md += "- URL: $($state.pr_info.url)`n"
        $md += "- Status: $($state.pr_info.status)`n"
    } else {
        $md += "- No PR opened yet.`n"
    }
    $md += "`n"
    
    $md += "## Local Verification (Fast-Feedback)`n"
    $md += "- Passed: $($state.verification.passed)`n"
    if ($state.verification.timestamp) {
        $md += "- Exit Code: $($state.verification.exit_code)`n"
        $md += "- Timestamp: $($state.verification.timestamp)`n"
    }
    $md += "`n"
    
    $md += "## Workstreams`n"
    if ($state.workstreams.PSObject.Properties.Count -eq 0) {
        $md += "*No workstreams defined.*`n"
    } else {
        foreach ($prop in $state.workstreams.PSObject.Properties) {
            $ws = $prop.Value
            $md += "- **$($prop.Name)**: $($ws.status)`n"
            $md += "  - Dependencies: $($ws.depends_on -join ', ')`n"
            $md += "  - Assigned: $($ws.assigned_agent_id)`n"
            $md += "  - Attempts: $($ws.attempts)`n"
        }
    }
    
    $md | Set-Content $TaskProjectionPath
}

Export-ModuleMember -Function Get-HarnessIntegrity, Invoke-FailClosed, Read-ExecutionState, Write-ExecutionState, Update-TaskProjection
