spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marziya_gold
    username: postgres
    password: on14881069
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
